[package]
name = "crater-engine"
version = "0.1.0"
authors = ["Brian Anderson <banderson@mozilla.com>"]

[lib]
name = "crater_engine"
path = "lib.rs"

[dependencies]
rustc-serialize = "*"

[dependencies.crater-msgbus]
path = "../crater-msgbus"